from pandas import read_csv

ns = read_csv('/mnt/HDD3/lrma/script/ns_subg.csv', index_col=0)
ns = ns.loc[ns['identity_filter']]

def get_subg(S):
    return [ns.loc[s, 'ref_nucmer'] for s in S]

rule all:
    input:
        expand('/mnt/HDD3/lrma/mummer_polished/{s}.coords', s=ns['s_subg'].values)

rule nucmer:
    input:
        polished='/mnt/HDD3/lrma/medaka/{s}/consensus.fasta'
    params:
        qm = get_subg
    output:
        '/mnt/HDD3/lrma/mummer_polished/{s}.delta'
    shell:
        'nucmer --mum --delta={output} {params.qm} {input.polished}'

rule show_coords:
    input:
        '/mnt/HDD3/lrma/mummer_polished/{s}.delta'
    output:
        '/mnt/HDD3/lrma/mummer_polished/{s}.coords'
    shell:
        'show-coords -drTH {input} > {output}'
