from pandas import read_csv
ns = read_csv('/mnt/HDD3/lrma/script/nano_strains.csv', index_col=0)

# define functions for use as input/params
def get_fastq(S):
    return [ns.loc[s, 'path'] for s in S]

rule all:
    input:
        expand('/mnt/HDD3/lrma/seqkit_stats/{s}.stats', s=ns.index)

rule seqkit:    
    params:
        reads = get_fastq
    output:
        stats = '/mnt/HDD3/lrma/seqkit_stats/{s}.stats'
    shell:
        'seqkit stats {params.reads} > {output.stats}'
