
from pandas import read_csv
ns = read_csv('/mnt/HDD3/lrma/script/ns_subg.csv', index_col=0)

# define functions for use as input/params
def get_subg(S):
    return [f'/home/mathieu/paradoxus_nanopore/MA_parents/assemblies/{ns.loc[s,"subg"]}.chromosomes.fasta' for s in S]

rule all:
    input:
        expand('/mnt/HDD3/lrma/svim-asm_draft/{s}/.{s}.output', s=ns.index)

rule svim:
    input:
        bam = '/mnt/HDD3/lrma/minimap_ref/{s}/{s}.sorted.bam'
    params:
        ref = get_subg
    output:
        '/mnt/HDD3/lrma/svim-asm_draft/{s}/.{s}.output'
    shell:
        'svim-asm haploid /mnt/HDD3/lrma/svim-asm_draft/{wildcards.s} {input.bam} {params.ref}; '
        'touch {output}'
