import os
from pandas import read_csv

ns = read_csv('/mnt/HDD3/lrma/script/nano_strains.csv', index_col=0)
ns = ns.loc[ns['cross']=='P']

for s in ns.index:
    path = f'/mnt/HDD3/lrma/indexcov/{s}/'
    if not os.path.exists(path):
        os.mkdir(path)

def get_reads(S):
    return [ns.loc[s, 'path'] for s in S]

rule all:
    input:
        expand('/mnt/HDD3/lrma/indexcov/{s}/{s}-indexcov.bed.gz', s=ns.index)

rule minimap2:
    input:
        ref = '/mnt/HDD1/paradoxus_nanopore/MA_parents/assemblies/{s}.chromosomes.rdna.fasta'
    params:
        reads = get_reads
    output:
        bam = '/mnt/HDD3/lrma/indexcov/{s}/{s}.ref.bam'
    shell:
        'minimap2 -a {input.ref} {params.reads} | samtools sort -T {wildcards.s} -o {output.bam}; '
        'samtools index {output.bam}'

rule indexcov:
    input:
        bam = '/mnt/HDD3/lrma/indexcov/{s}/{s}.ref.bam'
    params:
        dir = '/mnt/HDD3/lrma/indexcov/{s}/'
    output:
        bed = '/mnt/HDD3/lrma/indexcov/{s}/{s}-indexcov.bed.gz'
    shell:
        'goleft indexcov --directory {params.dir} {input.bam}'
