
from pandas import read_csv
ns = read_csv('/mnt/HDD3/lrma/script/ns_subg.csv', index_col=0)

# define functions for use as input/params
def get_fastq(S):
    return [ns.loc[s, 's_subg'] for s in S]

rule all:
    input:
        expand('/mnt/HDD3/lrma/minimap_polish/{s}.draft.minimap.bam', s=ns.index)

rule minimap:
    input:
        reads = '/mnt/HDD3/lrma/sort/{s}.reads.fastq',
        draft = '/mnt/HDD3/lrma/wtdbg2/{s}/{s}.cns.fa'
    output:
        '/mnt/HDD3/lrma/minimap_polish/{s}.draft.minimap.bam'
    shell: #filter out secondary alignments
        'minimap2 -x map-ont -t 2 -a {input.draft} {input.reads} | samtools sort -@ 1 -T tmp.{wildcards.s} | samtools view -F260 -o {output}; '
        'samtools index {output}; '
        'samtools stats {output} > {wildcards.s}.draft.minimap.stats'
