from pandas import read_csv
ns = read_csv('/mnt/HDD3/lrma/script/ns_subg.csv')
get_reads_dict = dict(zip(ns['strain'].values, ns['path'].values))

def get_reads(S):
    return [get_reads_dict[s] for s in S]

rule all:
    input:
        expand('/mnt/HDD3/lrma/sort/{s}.{g}.reads.fastq', zip, s=ns['strain'].values, g=ns['subg'].values)

rule cat:
    params:
        reads=get_reads
    output:
        temp('/mnt/HDD3/lrma/sort/combined.{s}.reads.fastq')
    shell:
        'zcat {params.reads} > {output}'

rule subseq:
    input:
        reads='/mnt/HDD3/lrma/sort/combined.{s}.reads.fastq',
        rid='/mnt/HDD3/lrma/sort/{s}.{g}.reads'
    output:
        '/mnt/HDD3/lrma/sort/{s}.{g}.reads.fastq'
    shell:
        'seqtk subseq {input.reads} {input.rid} > {output}'
