from pandas import read_csv

ns = read_csv('/mnt/HDD3/lrma/script/ns_subg.csv', index_col=0)
ns = ns.loc[ns['identity_filter']]

def get_subg(S):
    return [ns.loc[s, 'ref_chroder'] for s in S]

rule all:
    input:
        expand('/mnt/HDD3/lrma/syri/{s}/{s}.syri.vcf', s=ns['s_subg'].values)

rule syri:
    input:
        chroder='/mnt/HDD3/lrma/chroder/{s}.chroder.qry.fasta',
        coords='/mnt/HDD3/lrma/chroder/{s}.chroder.fil.coords',
        delta='/mnt/HDD3/lrma/chroder/{s}.chroder.fil.delta',
        ref = get_subg
    params:
        outdir = '/mnt/HDD3/lrma/syri/{s}'
    output:
        '/mnt/HDD3/lrma/syri/{s}/{s}.syri.vcf'
    shell:
        'export PATH_TO_SYRI=/home/mathieu/software/syri/syri/bin/syri; '
        'if [ ! -d  {params.outdir} ]; then mkdir {params.outdir}; fi; '
        'python3 $PATH_TO_SYRI -c {input.coords} -d {input.delta} -r {input.ref} -q {input.chroder} --prefix {wildcards.s}. --dir {params.outdir} --nosnp; '
        'if [ ! -f {output} ]; then touch {output}; fi'
