
from pandas import read_csv
ns = read_csv('/mnt/HDD3/lrma/script/ns_subg.csv', index_col=0)

# define functions for use as input/params
def get_fastq(S):
    return [ns.loc[s, 's_subg'] for s in S]

rule all:
    input:
        expand('/mnt/HDD3/lrma/svim_draft/{s}/.{s}.output', s=ns.index)

rule svim:
    input:
        bam = '/mnt/HDD3/lrma/minimap_polish/{s}.draft.minimap.bam',
        draft = '/mnt/HDD3/lrma/wtdbg2/{s}/{s}.cns.fa'
    output:
        '/mnt/HDD3/lrma/svim_draft/{s}/.{s}.output'
    shell:
        'if [ ! -d {wildcards.s} ]; then mkdir {wildcards.s}; fi; '
        'svim alignment {wildcards.s} {input.bam} {input.draft}; '
        'touch {output}'
